service: video-user-notifications

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    SQS_QUEUE_URL: http://localhost:9324/000000000000/video-user-notifications-queue

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
          Resource:
            Fn::GetAtt:
              - NotificationQueue
              - Arn

functions:
  notifyUser:
    handler: src/handlers/notifyUser.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - NotificationQueue
              - Arn
          batchSize: 1

resources:
  Resources:
    NotificationQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: video-user-notifications-queue

plugins:
  - serverless-plugin-typescript
  - serverless-offline-sqs
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: us-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
    queues:
      - name: video-user-notifications-queue
        url: http://localhost:9324/000000000000/video-user-notifications-queue
