service: video-user-notifications

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1

functions:
  notifyUser:
    handler: src/handlers/notifyUser.handler
    events:
      - sns:
          topicName: video-user-notification-topic

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000