service: video-user-notifications

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  version: v1

functions:
  notifyUser:
    handler: src/handlers/notifyUser.handler
    events:
      - sns:
          arn:
            Ref: NotificationTopic

resources:
  Resources:
    NotificationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: video-user-notification-topic

    LambdaInvokePermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Ref: NotifyUserLambdaFunction
        Action: lambda:InvokeFunction
        Principal: sns.amazonaws.com
        SourceArn:
          Ref: NotificationTopic

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
